export type VisitState = 'visited' | 'partial' | 'unvisited';

export type SubItem = {
  name: string;
  visited?: boolean;
  uncertain?: boolean;
};

export type HeritageSite = {
  id: string;
  name: string;
  category:
    | '古遗址'
    | '古墓葬'
    | '古建筑'
    | '石窟寺及石刻'
    | '近现代重要史迹及代表性建筑';
  era: string;
  district: string;
  address: string;
  lat: number;
  lng: number;
  photos?: string[];
  subItems?: SubItem[];
};

const asset = (path: string) => `${import.meta.env.BASE_URL || '/'}${path}`;
const p = (...names: string[]) =>
  names.map((name) => asset(`photos/${name}.jpg`));

export const officialSource =
  'https://wlj.nanjing.gov.cn/zwgk/wwbhml/202501/P020251127641809511607.pdf';

export const sites: HeritageSite[] = [
  {
    id: 'human-fossil',
    name: '南京人化石地点',
    category: '古遗址',
    era: '旧石器时代',
    district: '江宁区',
    address: '汤山街道302县道南侧雷公山葫芦洞',
    lat: 32.059386,
    lng: 119.039292,
    photos: p('IMG_3531'),
  },
  {
    id: 'zhongshan-ruins',
    name: '钟山建筑遗址',
    category: '古遗址',
    era: '六朝',
    district: '玄武区',
    address: '紫金山南坡海拔277米处',
    lat: 32.0659,
    lng: 118.8463,
  },
  {
    id: 'ming-palace',
    name: '明故宫遗址',
    category: '古遗址',
    era: '明代',
    district: '玄武区、秦淮区',
    address: '御道街至后宰门一带，中山东路南北两侧',
    lat: 32.039325,
    lng: 118.812303,
    photos: p('IMG_3238'),
  },
  {
    id: 'longjiang',
    name: '龙江船厂遗址',
    category: '古遗址',
    era: '明代',
    district: '鼓楼区',
    address: '江东街道漓江路57号',
    lat: 32.063756,
    lng: 118.730706,
    photos: p('IMG_0488'),
  },
  {
    id: 'xuecheng',
    name: '薛城遗址',
    category: '古遗址',
    era: '新石器时代',
    district: '高淳区',
    address: '淳溪街道薛城村薛十自然村',
    lat: 31.363417,
    lng: 118.850228,
    photos: p('IMG_7935'),
  },
  {
    id: 'gucheng',
    name: '固城遗址',
    category: '古遗址',
    era: '春秋至汉',
    district: '高淳区',
    address: '固城街道固游路两侧',
    lat: 31.312475,
    lng: 118.978333,
    photos: p('IMG_7948'),
  },
  {
    id: 'dabaoen',
    name: '大报恩寺遗址（含大报恩碑）',
    category: '古遗址',
    era: '东晋至清',
    district: '秦淮区',
    address: '雨花路1号',
    lat: 32.011636,
    lng: 118.776742,
    photos: p('IMG_0515'),
  },

  {
    id: 'mingxiaoling',
    name: '明孝陵',
    category: '古墓葬',
    era: '明代',
    district: '玄武区、雨花台区',
    address: '紫金山南麓及南京城内相关墓地',
    lat: 32.0623,
    lng: 118.8347,
    photos: p('IMG_0413', 'IMG_2469', 'IMG_3374', 'IMG_3375'),
    subItems: [
      { name: '明孝陵' },
      { name: '明东陵' },
      { name: '徐达墓' },
      { name: '李文忠墓' },
      { name: '吴良墓', uncertain: true },
      { name: '吴桢墓', uncertain: true },
      { name: '常遇春墓', visited: true },
      { name: '仇成墓石刻', visited: true },
      { name: '邓愈墓', visited: true },
      { name: '李杰墓' },
    ],
  },
  {
    id: 'southern-tang',
    name: '南唐二陵',
    category: '古墓葬',
    era: '五代',
    district: '江宁区',
    address: '秣陵街道祖堂山',
    lat: 31.889172,
    lng: 118.733506,
    photos: p('IMG_0255'),
  },
  {
    id: 'brunei-king',
    name: '浡泥国王墓',
    category: '古墓葬',
    era: '明代',
    district: '雨花台区',
    address: '软件大道乌龟山南麓',
    lat: 31.978207,
    lng: 118.752866,
    photos: p('IMG_4778', 'IMG_7260'),
  },
  {
    id: 'xiangshan-wang',
    name: '象山王氏家族墓地',
    category: '古墓葬',
    era: '东晋',
    district: '鼓楼区',
    address: '幕府西路象山',
    lat: 32.1058,
    lng: 118.7448,
  },
  {
    id: 'shangfang-wu',
    name: '上坊孙吴墓',
    category: '古墓葬',
    era: '三国',
    district: '江宁区',
    address: '上坊建茂村“孙家坟”',
    lat: 31.96589,
    lng: 118.9094,
  },
  {
    id: 'xianheguan',
    name: '仙鹤观六朝墓地',
    category: '古墓葬',
    era: '六朝',
    district: '栖霞区',
    address: '南京师范大学仙林校区西部',
    lat: 32.103047,
    lng: 118.899611,
    photos: p('IMG_2920'),
  },

  {
    id: 'city-wall',
    name: '南京城墙',
    category: '古建筑',
    era: '明代',
    district: '玄武区、秦淮区、鼓楼区',
    address: '南京明城墙现存各段',
    lat: 32.064383,
    lng: 118.793975,
    photos: p(
      'IMG_0203',
      'IMG_0917',
      'IMG_2116',
      'IMG_3163',
      'IMG_3174',
      'IMG_3182',
      'IMG_4093',
      'IMG_5286',
      'IMG_6317',
      'IMG_6517',
      'IMG_6843',
    ),
  },
  {
    id: 'qixia-pagoda',
    name: '栖霞寺舍利塔',
    category: '古建筑',
    era: '隋至五代',
    district: '栖霞区',
    address: '栖霞寺东南角',
    lat: 32.1538,
    lng: 118.95465,
    photos: p('IMG_1850'),
  },
  {
    id: 'zhanyuan',
    name: '瞻园',
    category: '古建筑',
    era: '明至清',
    district: '秦淮区',
    address: '瞻园路128号',
    lat: 32.022244,
    lng: 118.780206,
    photos: p('IMG_0685'),
  },
  {
    id: 'ganxi',
    name: '甘熙宅第',
    category: '古建筑',
    era: '清代',
    district: '秦淮区',
    address: '南捕厅15、17、19号，大板巷42号',
    lat: 32.028233,
    lng: 118.777581,
    photos: p('IMG_0977'),
  },
  {
    id: 'qiqiaoweng',
    name: '七桥瓮',
    category: '古建筑',
    era: '明代',
    district: '秦淮区',
    address: '红花街道秦淮河上',
    lat: 32.009164,
    lng: 118.824433,
    photos: p('IMG_6180'),
  },
  {
    id: 'putang-bridge',
    name: '蒲塘桥',
    category: '古建筑',
    era: '明代',
    district: '溧水区',
    address: '洪蓝街道蒲塘河上',
    lat: 31.56091,
    lng: 118.98957,
  },
  {
    id: 'chaotian-palace',
    name: '朝天宫',
    category: '古建筑',
    era: '明至清',
    district: '秦淮区',
    address: '朝天宫4号',
    lat: 32.034906,
    lng: 118.770242,
    photos: p('IMG_0986'),
  },
  {
    id: 'yangliu-village',
    name: '杨柳村古建筑群',
    category: '古建筑',
    era: '明清',
    district: '江宁区',
    address: '湖熟街道前杨柳村',
    lat: 31.86,
    lng: 118.921408,
    photos: p('IMG_4796'),
  },
  {
    id: 'drum-tower',
    name: '南京鼓楼',
    category: '古建筑',
    era: '明代',
    district: '鼓楼区',
    address: '北京西路1-1号',
    lat: 32.06073,
    lng: 118.77683,
  },

  {
    id: 'southern-dynasty-stone',
    name: '南京南朝陵墓石刻',
    category: '石窟寺及石刻',
    era: '南朝',
    district: '栖霞区、江宁区',
    address: '栖霞、江宁多处分布',
    lat: 32.064,
    lng: 118.92,
    photos: p(
      'IMG_5063',
      'IMG_5086',
      'IMG_5112',
      'IMG_5128',
      'IMG_5163',
      'IMG_5179',
      'IMG_5187',
      'IMG_7165',
      'IMG_7179',
      'IMG_7192',
      'IMG_7199',
      'IMG_7680',
      'IMG_7805',
      'IMG_7910',
    ),
    subItems: [
      { name: '徐家村失考墓石刻', visited: true },
      { name: '梁桂阳简王萧融墓石刻', visited: true },
      { name: '梁安成康王萧秀墓石刻', visited: true },
      { name: '梁始兴忠武王萧憺墓石刻', visited: true },
      { name: '梁吴平忠侯萧景墓石刻' },
      { name: '梁鄱阳忠烈王萧恢墓石刻', visited: true },
      { name: '梁临川靖惠王萧宏墓石刻', visited: true },
      { name: '陈文帝陈蒨永宁陵石刻', visited: true },
      { name: '北家边失考墓石刻' },
      { name: '梁建安敏侯萧正立墓石刻' },
      { name: '陈武帝陈霸先万安陵石刻', visited: true },
      { name: '宋武帝刘裕初宁陵石刻', visited: true },
      { name: '宋墅失考墓石刻', visited: true },
      { name: '侯村失考墓石刻', uncertain: true },
      { name: '方旗庙失考墓石刻', uncertain: true },
      { name: '耿岗失考墓石刻', visited: true },
      { name: '萧伟墓石刻', visited: true },
    ],
  },
  {
    id: 'qianfo-cliff',
    name: '千佛崖石窟及明征君碑',
    category: '石窟寺及石刻',
    era: '南朝至明',
    district: '栖霞区',
    address: '栖霞寺内',
    lat: 32.1539,
    lng: 118.954,
    photos: p('IMG_1844', 'IMG_1853'),
    subItems: [
      { name: '千佛崖石窟', visited: true },
      { name: '明征君碑', visited: true },
    ],
  },
  {
    id: 'yangshan-stele',
    name: '阳山碑材',
    category: '石窟寺及石刻',
    era: '明代',
    district: '江宁区',
    address: '汤山街道坟头村阳山南麓',
    lat: 32.0583,
    lng: 119.0567,
  },

  {
    id: 'sun-yat-sen-mausoleum',
    name: '中山陵',
    category: '近现代重要史迹及代表性建筑',
    era: '民国',
    district: '玄武区',
    address: '钟山风景名胜区',
    lat: 32.06018,
    lng: 118.84854,
    photos: p(
      'IMG_0785',
      'IMG_2578',
      'IMG_2580',
      'IMG_2584',
      'IMG_2586',
      'IMG_2590',
    ),
    subItems: [
      { name: '中山陵' },
      { name: '邓演达墓', visited: true },
      { name: '廖仲恺何香凝墓', visited: true },
      { name: '谭延闿墓', visited: true },
      { name: '国民革命军阵亡将士公墓', visited: true },
      { name: '中山陵附属革命历史图书馆' },
    ],
  },
  {
    id: 'taiping-palace',
    name: '太平天国天王府遗址',
    category: '近现代重要史迹及代表性建筑',
    era: '清代',
    district: '玄武区',
    address: '长江路292号',
    lat: 32.045114,
    lng: 118.792519,
    photos: p('IMG_4408'),
  },
  {
    id: 'tangzi-murals',
    name: '堂子街太平天国壁画',
    category: '近现代重要史迹及代表性建筑',
    era: '清代',
    district: '秦淮区',
    address: '堂子街108号',
    lat: 32.0322,
    lng: 118.7711,
  },
  {
    id: 'yuhuatai',
    name: '雨花台烈士陵园',
    category: '近现代重要史迹及代表性建筑',
    era: '1927—1949年',
    district: '雨花台区',
    address: '雨花路215号',
    lat: 32.0017,
    lng: 118.779014,
    photos: p('IMG_0694'),
  },
  {
    id: 'zijin-observatory',
    name: '国立紫金山天文台旧址',
    category: '近现代重要史迹及代表性建筑',
    era: '民国',
    district: '玄武区',
    address: '紫金山天堡山',
    lat: 32.067769,
    lng: 118.824081,
    photos: p('IMG_3372'),
  },
  {
    id: 'meiyuan',
    name: '中国共产党代表团办事处旧址',
    category: '近现代重要史迹及代表性建筑',
    era: '1946—1947年',
    district: '玄武区',
    address: '梅园新村17、30、35号',
    lat: 32.044247,
    lng: 118.796211,
    photos: p('IMG_4419'),
  },
  {
    id: 'national-government',
    name: '原国民政府旧址',
    category: '近现代重要史迹及代表性建筑',
    era: '民国',
    district: '玄武区、鼓楼区',
    address: '南京城内多处分布',
    lat: 32.048764,
    lng: 118.840431,
    photos: p('IMG_0994', 'IMG_2130'),
    subItems: [
      { name: '国民政府考试院旧址' },
      { name: '国民政府主席官邸旧址', visited: true },
      { name: '国民党中央监察委员会办公楼旧址', visited: true },
      { name: '国民党中央党史史料陈列馆旧址' },
      { name: '国民政府外交部旧址' },
      { name: '国民政府最高法院旧址' },
      { name: '国民政府行政院旧址' },
      { name: '国民政府交通部旧址' },
      { name: '临时政府参议院旧址' },
    ],
  },
  {
    id: 'central-stadium',
    name: '中央体育场旧址',
    category: '近现代重要史迹及代表性建筑',
    era: '民国',
    district: '玄武区',
    address: '灵谷寺路8号',
    lat: 32.045272,
    lng: 118.862892,
    photos: p('IMG_0817'),
  },
  {
    id: 'national-hall',
    name: '国民大会堂旧址',
    category: '近现代重要史迹及代表性建筑',
    era: '民国',
    district: '玄武区',
    address: '长江路264号',
    lat: 32.046383,
    lng: 118.787942,
    photos: p('IMG_4406'),
  },
  {
    id: 'central-university',
    name: '中央大学旧址（含梅庵）',
    category: '近现代重要史迹及代表性建筑',
    era: '民国',
    district: '玄武区',
    address: '四牌楼2号',
    lat: 32.005886,
    lng: 118.773872,
    photos: p('IMG_0699'),
  },
  {
    id: 'ginling-university',
    name: '金陵大学旧址',
    category: '近现代重要史迹及代表性建筑',
    era: '民国',
    district: '鼓楼区',
    address: '汉口路22号、中山北路169号',
    lat: 32.057372,
    lng: 118.775742,
    photos: p('IMG_0921'),
    subItems: [
      { name: '金陵大学旧址', visited: true },
      { name: '汇文书院钟楼' },
    ],
  },
  {
    id: 'ginling-women',
    name: '金陵女子大学旧址',
    category: '近现代重要史迹及代表性建筑',
    era: '民国',
    district: '鼓楼区',
    address: '宁海路122号',
    lat: 32.0596,
    lng: 118.7731,
  },
  {
    id: 'massacre-burial',
    name: '侵华日军南京大屠杀死难同胞丛葬地',
    category: '近现代重要史迹及代表性建筑',
    era: '1937年',
    district: '多区',
    address: '南京城内外17处',
    lat: 32.0382,
    lng: 118.7396,
    photos: p('IMG_3177', 'IMG_5289', 'IMG_7376'),
    subItems: [
      { name: '北极阁' },
      { name: '中山陵西洼子村' },
      { name: '正觉寺', visited: true },
      { name: '上新河' },
      { name: '江东门' },
      { name: '汉中门外' },
      { name: '煤炭港' },
      { name: '中山码头' },
      { name: '鱼雷营' },
      { name: '草鞋峡' },
      { name: '挹江门', visited: true },
      { name: '金陵大学' },
      { name: '清凉山' },
      { name: '五台山', visited: true },
      { name: '普德寺' },
      { name: '花神庙' },
      { name: '燕子矶' },
    ],
  },
  {
    id: 'jinling-press',
    name: '金陵刻经处',
    category: '近现代重要史迹及代表性建筑',
    era: '清代',
    district: '秦淮区',
    address: '淮海路35号',
    lat: 32.038781,
    lng: 118.785492,
    photos: p('IMG_0898'),
  },
  {
    id: 'jinling-arsenal',
    name: '金陵兵工厂旧址',
    category: '近现代重要史迹及代表性建筑',
    era: '清末至民国',
    district: '秦淮区',
    address: '应天大街388号',
    lat: 32.0189,
    lng: 118.7551,
  },
  {
    id: 'pukou-station',
    name: '浦口火车站旧址',
    category: '近现代重要史迹及代表性建筑',
    era: '民国',
    district: '浦口区',
    address: '津浦路30号',
    lat: 32.098161,
    lng: 118.716331,
    photos: p('IMG_4014'),
  },
  {
    id: 'presidential-palace',
    name: '孙中山临时大总统府及南京国民政府建筑遗存',
    category: '近现代重要史迹及代表性建筑',
    era: '民国',
    district: '玄武区',
    address: '长江路292号',
    lat: 32.045119,
    lng: 118.792258,
    photos: p('IMG_4409'),
  },
  {
    id: 'beijige-weather',
    name: '北极阁气象台旧址',
    category: '近现代重要史迹及代表性建筑',
    era: '民国',
    district: '玄武区',
    address: '北极阁2号',
    lat: 32.0598,
    lng: 118.7949,
  },
  {
    id: 'whampoa-nanjing',
    name: '中央陆军军官学校旧址',
    category: '近现代重要史迹及代表性建筑',
    era: '民国',
    district: '玄武区',
    address: '黄埔路1号',
    lat: 32.0459,
    lng: 118.8077,
  },
  {
    id: 'lizhishe',
    name: '励志社旧址',
    category: '近现代重要史迹及代表性建筑',
    era: '民国',
    district: '玄武区',
    address: '中山东路307号',
    lat: 32.042328,
    lng: 118.806739,
    photos: p('IMG_3274'),
  },
  {
    id: 'central-radio',
    name: '国民政府中央广播电台旧址',
    category: '近现代重要史迹及代表性建筑',
    era: '民国',
    district: '鼓楼区',
    address: '江东门北街33号',
    lat: 32.0422,
    lng: 118.7352,
  },
  {
    id: 'academia-sinica',
    name: '国立中央研究院旧址',
    category: '近现代重要史迹及代表性建筑',
    era: '民国',
    district: '玄武区',
    address: '北京东路39号',
    lat: 32.041125,
    lng: 118.791892,
    photos: p('IMG_0899'),
  },
  {
    id: 'rabe-house',
    name: '拉贝旧居',
    category: '近现代重要史迹及代表性建筑',
    era: '民国',
    district: '鼓楼区',
    address: '小粉桥1号',
    lat: 32.052636,
    lng: 118.777992,
    photos: p('IMG_7252'),
  },
  {
    id: 'us-embassy',
    name: '美国驻华使馆旧址',
    category: '近现代重要史迹及代表性建筑',
    era: '民国',
    district: '鼓楼区',
    address: '西康路33号',
    lat: 32.065297,
    lng: 118.758369,
    photos: p('IMG_3965'),
  },
  {
    id: 'uk-embassy',
    name: '英国驻华使馆旧址',
    category: '近现代重要史迹及代表性建筑',
    era: '民国',
    district: '鼓楼区',
    address: '虎踞北路185号',
    lat: 32.085217,
    lng: 118.748292,
    photos: p('IMG_3595'),
  },
  {
    id: 'eighth-route-office',
    name: '八路军驻南京办事处旧址',
    category: '近现代重要史迹及代表性建筑',
    era: '1937年',
    district: '鼓楼区',
    address: '傅后岗66号、高云岭29号',
    lat: 32.0661,
    lng: 118.7796,
    subItems: [{ name: '傅后岗66号' }, { name: '高云岭29号' }],
  },
  {
    id: 'liji-lane',
    name: '侵华日军南京利济巷慰安所旧址',
    category: '近现代重要史迹及代表性建筑',
    era: '1937—1945年',
    district: '秦淮区',
    address: '利济巷2号',
    lat: 32.0408,
    lng: 118.7987,
  },
  {
    id: 'malin-hospital',
    name: '马林医院旧址',
    category: '近现代重要史迹及代表性建筑',
    era: '民国',
    district: '鼓楼区',
    address: '汉中路140号',
    lat: 32.041,
    lng: 118.7672,
  },
  {
    id: 'national-art-gallery',
    name: '国立美术陈列馆旧址',
    category: '近现代重要史迹及代表性建筑',
    era: '民国',
    district: '玄武区',
    address: '长江路266号',
    lat: 32.0466,
    lng: 118.7885,
  },
  {
    id: 'japanese-embassy',
    name: '日本驻南京大使馆旧址',
    category: '近现代重要史迹及代表性建筑',
    era: '民国',
    district: '鼓楼区',
    address: '鼓楼区上海路一带',
    lat: 32.0506,
    lng: 118.7741,
  },
];

export function getVisitState(site: HeritageSite): VisitState {
  if (site.subItems?.length) {
    const visited = site.subItems.filter((item) => item.visited).length;
    if (visited === site.subItems.length) return 'visited';
    if (visited > 0 || site.photos?.length) return 'partial';
    return 'unvisited';
  }
  return site.photos?.length ? 'visited' : 'unvisited';
}

export const photoCount = new Set(sites.flatMap((site) => site.photos ?? []))
  .size;
export const pendingConfirmations = [
  {
    id: 'wu-tombs',
    siteId: 'mingxiaoling',
    photo: asset('photos/IMG_0413.jpg'),
    title: '吴良墓，还是吴桢墓？',
    note: '照片中的文保碑同时写有“吴良、吴桢墓”，仅凭照片无法判断你实际走到哪一座。',
    options: ['吴良墓', '吴桢墓', '两处都去了'],
  },
  {
    id: 'jiangning-stone-1',
    siteId: 'southern-dynasty-stone',
    photo: asset('photos/IMG_7192.jpg'),
    title: '这处失考墓石刻的子项名称',
    note: '碑名在原片中距离较远；结合位置推测为侯村失考墓石刻，但需要你确认。',
    options: ['侯村失考墓石刻', '梁建安敏侯萧正立墓石刻', '暂不确定'],
  },
  {
    id: 'jiangning-stone-2',
    siteId: 'southern-dynasty-stone',
    photo: asset('photos/IMG_7910.jpg'),
    title: '方旗庙失考墓石刻？',
    note: '照片只清楚拍到“南京南朝陵墓石刻”总名；按拍摄坐标推测为方旗庙失考墓石刻。',
    options: ['方旗庙失考墓石刻', '其他子项', '暂不确定'],
  },
];
